stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  TF_VAR_aws_access_key: $AWS_ACCESS_KEY_ID
  TF_VAR_aws_secret_key: $AWS_SECRET_ACCESS_KEY
  TF_VAR_aws_region: $AWS_DEFAULT_REGION
  TF_VAR_gitlab_ssh_public: $GITLAB_SSH_PUBLIC
  TF_VAR_ec2_ssh_private: $EC2_SSH_PRIVATE
  TF_VAR_secrets_ini: $SECRETS_INI

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

.terraform_job:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"  # Only run on main branch
      when: always
    - if: $CI_COMMIT_REF_NAME == "network_rds"  # TESTING
      when: always
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never  # Prevention of running on merge requests
    - when: never  # Don't run on any other branch

before_script:
  - cd infrastructure/
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  extends: .terraform_job
  stage: validate
  script:
    - terraform validate

plan:
  extends: .terraform_job
  stage: plan
  script:
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ./infrastructure/tfplan

apply:
  extends: .terraform_job
  stage: apply
  script:
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  artifacts:
    paths:
      - ./infrastructure/terraform.tfstate

destroy:
  extends: .terraform_job
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  allow_failure: false
  dependencies: 
    - apply
